In [1]:
import numpy as np
my_array1 = np.array([1,2,3,4])
print(my_array1)

[1 2 3 4]


In [4]:
import numpy as np

my_array2 = np.array( [[1,2,3,4],[5,6,7,8],[9,10,11,12]] )
print(my_array2)
print(my_array2[0,2])
print(my_array2[0,0])
print(my_array2[2,2])
print(my_array2[1,0])
#Task2

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
3
1
11
5


In [9]:
#Task3
#3.1 use indexing to print out the element holding number 3 in my_array3.
#3.2 use indexing to print out the element holding number 1 in my_array3.
#3.3 use indexing to print out the element holding number 24 in my_array3.
#3.4 use indexing to print out the element holding number 35 in my_array3.
#3.5 use indexing to print out the element holding number 24 in my_array3.
#3.6 use indexing to print out the element holding number 18 in my_array3.
#3.7 use indexing to print out the element holding number 12 in my_array3.

import numpy as np
sheet1 = np.array( [[1,2,3,4],[5,6,7,8],[9,10,11,12]] )
sheet2 = np.array( [[13,14,15,16],[17,18,19,20],[21,22,23,24]] )
sheet3 = np.array( [[25,26,27,28],[29,30,31,32],[33,34,35,36]] )

my_array3=np.array([sheet1,sheet2,sheet3])
print(my_array3)
print(my_array3[0,0,2])
print(my_array3[0,0,0])
print(my_array3[1,2,3])
print(my_array3[1,1,1])
print(my_array3[0,2,3])


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]]
3
1
24
18
12


In [19]:
#Task4
import numpy as np
sheet1 = np.array( [[1,2,3,4],[5,6,7,8],[9,10,11,12]] )
sheet2 = np.array( [[13,14,15,16],[17,18,19,20],[21,22,23,24]] )
sheet3 = np.array( [[25,26,27,28],[29,30,31,32],[33,34,35,36]] )
workbook1=np.array([sheet1,sheet2,sheet3])

sheet4 = np.array( [[37,38,39,40],[41,42,43,44],[45,46,47,48]] )
sheet5 = np.array( [[49,50,51,52],[53,54,55,56],[57,58,59,60]] )
sheet6 = np.array( [[61,62,63,64],[65,66,67,68],[69,70,71,72]] )
workbook2=np.array([sheet4,sheet5,sheet6])

sheet7 = np.array( [[73,74,75,76],[77,78,79,80],[81,82,83,84]] )
sheet8 = np.array( [[85,86,87,88],[89,90,91,92],[93,94,95,96]] )
sheet9 = np.array( [[97,98,99,100],[101,102,103,104],[105,106,107,108]] )
workbook3=np.array([sheet7,sheet8,sheet9])

my_array4=np.array([workbook1,workbook2,workbook3])

print(my_array4)
"""4.1 use indexing to print out the element holding number 3 in my_array4.
4.2 use indexing to print out the element holding number 1 in my_array4.
4.3 use indexing to print out the element holding number 13 in my_array4.
4.4 use indexing to print out the element holding number 73 in my_array4.
4.5 use indexing to print out the element holding number 56 in my_array4.
4.6 use indexing to print out the element holding number 85 in my_array4.
4.7 use indexing to print out the element holding number 108 in my_array4."""
print(my_array4[0,0,0,2])
print(my_array4[0,1,0,0])
print(my_array4[0,0,0,0])
print(my_array4[0,0,0,2])
print(my_array4[2,0,0,0])
print(my_array4[1,1,1,3])
print(my_array4[2,2,2,3])

[[[[  1   2   3   4]
   [  5   6   7   8]
   [  9  10  11  12]]

  [[ 13  14  15  16]
   [ 17  18  19  20]
   [ 21  22  23  24]]

  [[ 25  26  27  28]
   [ 29  30  31  32]
   [ 33  34  35  36]]]


 [[[ 37  38  39  40]
   [ 41  42  43  44]
   [ 45  46  47  48]]

  [[ 49  50  51  52]
   [ 53  54  55  56]
   [ 57  58  59  60]]

  [[ 61  62  63  64]
   [ 65  66  67  68]
   [ 69  70  71  72]]]


 [[[ 73  74  75  76]
   [ 77  78  79  80]
   [ 81  82  83  84]]

  [[ 85  86  87  88]
   [ 89  90  91  92]
   [ 93  94  95  96]]

  [[ 97  98  99 100]
   [101 102 103 104]
   [105 106 107 108]]]]
3
13
1
3
73
56
108


In [35]:
#TASK 5 : create a zero-dimensional numpy arrays:
#5.1 with value 35
#5.1 with value 109
import numpy as np
my_array5=np.array(35)
print(my_array5)
print("dimesion:",my_array5.ndim)

my_array51=np.array(109)
print(my_array51)
print("dimesion:",my_array51.ndim)

35
dimesion: 0
109
dimesion: 0


In [39]:
#TASK 6 : create a one-dimensional numpy arrays:
#6.1 with 4 elements, use any values you like
#6.2 with 8 elements, use any values you like

import numpy as np
first=np.array([1,2,3,4])
print(first)
print("dimesion",first.ndim)

second=np.array([1,2,3,4,5,6,7,8,])
print(second)
print("dimesion",second.ndim)



[1 2 3 4]
dimesion 1
[1 2 3 4 5 6 7 8]
dimesion 1


In [44]:
#TASK 7 : create a two-dimensional numpy arrays :
##7.1 with 3 x 4 elements. Use any values you like.
#7.2 with 2 x 5 elements. Use any values you like.

#Optional, challenging task :
#create a two-dimensional numpy array with 1 x 1 elements. Use any value you like.

import numpy as np

task7=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(task7)
print("dimesion:",task7.ndim)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
dimesion: 2


In [46]:
task71=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(task71)
print(task71.ndim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2


In [50]:
#TASK 8 : create a three-dimensional numpy arrays :¶
#8.1 with 2 x 3 x 4 elements, use any values you like
#8.1 with 4 x 3 x 2 elements, use any values you like

task8=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(task8)
print("dimesion:",task8.ndim)


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
dimesion: 3


In [52]:
task81=np.array([[[1,2],[3,6],[7,8]]])
print(task81)
print("dimesion:",task81.ndim)

[[[1 2]
  [3 6]
  [7 8]]]
dimesion: 3


In [55]:
#TASK 9 : create the following arrays by using range()-function
#EXAMPLE :



my_array=np.array([range(4),range(4)])
print(my_array)
print(my_array.ndim)

[[0 1 2 3]
 [0 1 2 3]]
2


In [20]:
array92=np.array([range(4),range(4,8)])
print(array92)

[[0 1 2 3]
 [4 5 6 7]]


In [34]:
import numpy as np
array93=np.array([range(0,4,1), range(4,8,1), range(8,4,-1), range(4,0,-1)])
print(array93)

[[0 1 2 3]
 [4 5 6 7]
 [8 7 6 5]
 [4 3 2 1]]


In [38]:
array94=np.array([range(0,8,2),range(8,16,2),range(16,8,-2),range(8,0,-2)])
print(array94)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 14 12 10]
 [ 8  6  4  2]]


In [48]:
array95=np.array([range(0,100,10),range(100,1100,100)])
print(array95)

[[   0   10   20   30   40   50   60   70   80   90]
 [ 100  200  300  400  500  600  700  800  900 1000]]


In [60]:
array97=np.array([range(1000,0,-100)])
print(array97)

[[1000  900  800  700  600  500  400  300  200  100]]


In [61]:
another_array=np.array([[range(0,100,10),range(100,1100,100)],[range(1000,0,-100),range(90,-10,-10)]])
print(another_array)

[[[   0   10   20   30   40   50   60   70   80   90]
  [ 100  200  300  400  500  600  700  800  900 1000]]

 [[1000  900  800  700  600  500  400  300  200  100]
  [  90   80   70   60   50   40   30   20   10    0]]]
