In [1]:
import pandas as pd

In [5]:
import numpy as np
import pandas as pd

my_numpy_array = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(my_numpy_array)
print("dimension = ",my_numpy_array.ndim)
my_dataframe=pd.DataFrame(my_numpy_array)
my_dataframe.head(10)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
dimension =  2


0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12

In [10]:
import numpy as np
import pandas as pd

my_numpy_array = np.array([[18,168],[23,168],[43,191]])
print(my_numpy_array)

my_dataframe=pd.DataFrame(my_numpy_array,columns=["age","height"])
my_dataframe.head(10)

[[ 18 168]
 [ 23 168]
 [ 43 191]]


age  height
0   18     168
1   23     168
2   43     191

In [39]:
# TASK 2
# Create the DataFrame below :
# 2.1 create ndarray with the values
# 2.2 convert ndarray into DataFrame and define column names
# 2.3 add new column with string-values
import numpy as np
import pandas as pd

my_array=np.array([[29.0,28.6,27.5],[83.0,92.0,88.0]]).T
print(my_array)
my_data_frame =pd.DataFrame(my_array,columns=['bmi','waist'])

my_data_frame['sex']=(['woman','man','woman'])
my_data_frame.head()


[[29.  83. ]
 [28.6 92. ]
 [27.5 88. ]]


bmi  waist    sex
0  29.0   83.0  woman
1  28.6   92.0    man
2  27.5   88.0  woman

In [47]:
# TASK 3
# Create the DataFrame below :
# 2.1 create ndarray with the values and transpose
# 2.2 convert ndarray into DataFrame and define column names
# 2.3 add new column with string-values
import numpy as np
import pandas as pd

my_array=np.array([range(10)]).T
print(my_array)

my_df= pd.DataFrame(my_array,columns=["first columns"])
my_df["second"] =(range(10,20))
my_df.head(10)


[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


first columns  second
0              0      10
1              1      11
2              2      12
3              3      13
4              4      14
5              5      15
6              6      16
7              7      17
8              8      18
9              9      19